<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'm3f9aVyHwX8h8REG');
define('DB_HOST', 'gizurcloud.colm85rhpnd4.eu-west-1.rds.amazonaws.com');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');



?>
