<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');

/* Adapted to Heroku, see below
define('DB_USER', 'testlink');
define('DB_PASS', '2EuDneBJX54RTrbu');
define('DB_HOST', 'int-mysql-master.gizurcloud.com');
define('DB_NAME', 'testlink');
*/
define('DB_TABLE_PREFIX', '');


/*
 * Heroku MySQL setup
 */

if (isset($_SERVER["DATABASE_URL"])) {
 $db = parse_url($_SERVER["DATABASE_URL"]);
 define("DB_NAME", trim($db["path"],"/"));
 define("DB_USER", $db["user"]);
 define("DB_PASS", $db["pass"]);
 define("DB_HOST", $db["host"]);
}
else {
 die("Your heroku DATABASE_URL does not appear to be correctly specified.");
}

?>
