<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', '2EuDneBJX54RTrbu');
define('DB_HOST', 'int-mysql-master.gizurcloud.com');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
?>